name: Pull Request Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
    - run: npm install
    - run: npm run lint
    - run: npm run build:prod --if-present